name: bex-cli
title: bex
base: core22
version: git
summary: Better EXception Handling
description: Tool for a better exception handling
grade: stable
confinement: strict
icon: images/logo.png
license: CC0-1.0
architectures: [amd64, arm64]

parts:
  bex:
    source: https://github.com/BetterException/bex/archive/refs/tags/0.1.tar.gz
    source-type: tar
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
    build-packages:
      - cmake
      - g++
      - libssl-dev
