name: bex-cli
title: bex
base: core22
version: git
summary: Better EXception Handling
description: Tool for a better exception handling
grade: stable
confinement: strict
icon: images/logo.png
license: CC0-1.0
architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  bex:
    # This points to the location INSIDE the snap (where you saw it)
    command: usr/bin/bex
    # Optional: helps if your tool needs access to system resources
    plugs: [home, network]

parts:
  bex:
    source: https://github.com/BetterException/bex/archive/refs/tags/0.2.tar.gz
    source-type: tar
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/bin
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
    build-packages:
      - cmake
      - g++
      - libssl-dev
