name: Release
on:
  workflow_dispatch:
    inputs:
      major_version:
        description: "Major tag for release"
        required: true
        type: string
      minor_version:
        description: "Minor tag for release"
        required: true
        type: string
permissions:
  contents: write

jobs:
  windows-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Changing the required files for the release
        run: |
          sed -i '4s/.*/$version = "${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}"/' ./dist/windows/tools/chocolateyInstall.ps1
          sed -i '5s/.*/    <version>${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}<\/version>/' ./dist/windows/bex.nuspec
          sed -i '19s/.*/    source: https:\/\/github.com\/BetterException\/bex\/archive\/refs\/tags\/${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.tar.gz/' ./snapcraft.yaml
          sed -i '7s/.*/SET(BEX_MAJOR_VERSION ${{ github.event.inputs.major_version }} CACHE STRING "Major Version")/' ./CMakeLists.txt
          sed -i '8s/.*/SET(BEX_MINOR_VERSION ${{ github.event.inputs.minor_version }} CACHE STRING "Minor Version")/' ./CMakeLists.txt
          sed -i '3s/.*/    rev: "${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}"/' ./.pre-commit-config.yaml

          get-content ./dist/windows/tools/chocolateyInstall.ps1
          get-content ./dist/windows/bex.nuspec
          get-content ./snapcraft.yaml
          get-content ./CMakeLists.txt
          get-content ./.pre-commit-config.yaml
          git status

      - name: Building with CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING=OFF
          -DCMAKE_INSTALL_PREFIX="./app"
          -S .

      - name: Installing with CMake
        run: >
          cmake --build build --target install --config Release

      - name: Listing the contents of OpenSSL dir (Debug)
        run: |
          ls "C:\Program Files\OpenSSL"
          ls "C:\Program Files\OpenSSL\bin"

      - name: Finding the required dependencies
        run: |
          Copy-Item (Get-ChildItem -Path "C:\Program Files\OpenSSL\bin" -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libcrypto-1_1-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item (Get-ChildItem -Path "C:\Program Files\OpenSSL\bin" -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libssl-1_1-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item "C:\Windows\System32\msvcp140.dll" -Destination './app'
          Copy-Item "C:\Windows\System32\vcruntime140.dll" -Destination './app'

      - uses: actions/upload-artifact@v4
        id: artifact-upload-windows
        with:
          name: bex-win64
          path: ./app/
          compression-level: 9

      - name: Changing the hash in chocolateyInstall.ps1 file
        env:
          hash: ${{ steps.artifact-upload-windows.outputs.artifact-digest }}
        run: |
          sed -i '7s/.*/$hash = "${{ env.hash }}"/' ./dist/windows/tools/chocolateyInstall.ps1
          get-content ./dist/windows/tools/chocolateyInstall.ps1
          git status

      - name: Downloading the artifact and verifying the hash
        env:
          id: ${{ steps.artifact-upload-windows.outputs.artifact-id }}
        run: |
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_RELEASE_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/BetterException/bex/actions/artifacts/${{ env.id }}/zip -o bex-win64.zip
          openssl dgst -sha256 bex-win64.zip

      - name: Listing the directory contents (Debug)
        run: |
          ls
          ls ./app

      - name: Creating a release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ./bex-win64.zip
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          tag_name: ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}
          draft: false
          prerelease: false

      - name: Committing the changes for all the modified files
        run: |
          Remove-Item -Recurse -Force -Path "./app"
          rm -Force "./bex-win64.zip"
          git config --global user.email "48472541+GhostVaibhav@users.noreply.github.com"
          git config --global user.name "GhostVaibhav"
          git add .
          git commit -m "Release: ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}"
          git push

      - name: Creating a release on Chocolatey
        run: |
          choco pack ./dist/windows/bex.nuspec
          choco apiKey -k ${{ secrets.CHOCO_TOKEN }} -source https://push.chocolatey.org/
          choco push --source https://push.chocolatey.org/

  homebrew-release:
    runs-on: ubuntu-latest
    needs: windows-release

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "BetterException/homebrew-bex"
          token: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Download the release
        run: |
          curl -L --insecure "https://github.com/BetterException/bex/archive/refs/tags/${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.tar.gz" -o "${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.tar.gz"

      - name: Changing the required files for the release
        run: |
          sed -i '4s/.*/  url "https:\/\/github.com\/BetterException\/bex\/archive\/refs\/tags\/${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.tar.gz"/' ./bex.rb
          export HASH=$(sha256sum "${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.tar.gz" | cut -d ' ' -f 1)
          sed -i -e "5s/.*/  sha256 "$HASH"/" ./bex.rb

      - name: Removing the downloaded release
        run: |
          rm -f "${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.tar.gz"

      - name: Committing the changes for all the modified files
        run: |
          git config --global user.email "48472541+GhostVaibhav@users.noreply.github.com"
          git config --global user.name "GhostVaibhav"
          git add .
          git commit -m "Release: ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}"
          git push
