name: Release on Windows platform
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Building with CMake
        run: >
          cmake -B build
                -DCMAKE_BUILD_TYPE=Release
                -DBUILD_TESTING=OFF
                -DCMAKE_INSTALL_PREFIX="./app"
                -S .

      - name: Installing with CMake
        run: >
          cmake --build . --target install --config Release

      - name: Zipping the required files
        run: >
          Compress-Archive -Path ./app/* -DestinationPath "windows.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: windows.zip
          path: windows.zip
