name: Release on Windows platform
on:
  workflow_dispatch:

jobs:
  win-release:
    runs-on: windows-latest
    outputs:
      artifact-url: ${{ steps.artifact-upload-windows.outputs.artifact-url }}
      artifact-sha: ${{ steps.artifact-upload-windows.outputs.artifact-digest }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Building with CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING=OFF
          -DCMAKE_INSTALL_PREFIX="./app"
          -S .

      - name: Installing with CMake
        run: >
          cmake --build build --target install --config Release

      - name: Listing the contents of OpenSSL dir (Debug)
        run: |
          ls "C:\Program Files\OpenSSL"
          ls "C:\Program Files\OpenSSL\bin"

      - name: Finding the required dependencies
        run: |
          Copy-Item (Get-ChildItem -Path "C:\Program Files\OpenSSL\bin" -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libcrypto-1_1-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item (Get-ChildItem -Path "C:\Program Files\OpenSSL\bin" -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libssl-1_1-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item "C:\Windows\System32\msvcp140.dll" -Destination './app'
          Copy-Item "C:\Windows\System32\vcruntime140.dll" -Destination './app'

      - uses: actions/upload-artifact@v4
        id: artifact-upload-windows
        with:
          name: bex-win64
          path: ./app/
          compression-level: 9

      - name: Changing the chocolateyInstall file
        run: |
          sed -i '7s/.*/$hash = "${{ needs.artifact-sha }}"/' ./dist/windows/tools/chocolateyInstall.ps1
          get-content ./dist/windows/tools/chocolateyInstall.ps1

      # - name: Creating a release on Chocolatey
      #   run: |
      #     choco pack ./dist/windows/bex.nuspec
      #     choco apiKey -k ${{ secrets.CHOCO_TOKEN }} -source https://push.chocolatey.org/
      #     choco push --source https://push.chocolatey.org/
