name: Release on Windows platform
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Building with CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING=OFF
          -DCMAKE_INSTALL_PREFIX="./app"
          -S .

      - name: Installing with CMake
        run: >
          cmake --build build --target install --config Release

      - name: Finding the required dependencies
        run: |
          Copy-Item (Get-ChildItem -Path $env:ProgramFiles -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libcrypto-3-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item (Get-ChildItem -Path $env:ProgramFiles -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libssl-3-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item "C:\Windows\System32\msvcp140.dll" -Destination './app'
          Copy-Item "C:\Windows\System32\vcruntime140.dll" -Destination './app'

      - name: Zipping the required files
        run: >
          Compress-Archive -Path ./app/* -DestinationPath "windows.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: win64
          path: windows.zip
