name: Release on Windows platform
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Building with CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING=OFF
          -DCMAKE_INSTALL_PREFIX="./app"
          -S .

      - name: Installing with CMake
        run: >
          cmake --build build --target install --config Release

      - name: Listing the contents of OpenSSL dir (Debug)
        run: |
          ls "C:\Program Files\OpenSSL"
          ls "C:\Program Files\OpenSSL\bin"

      - name: Finding the required dependencies
        run: |
          Copy-Item (Get-ChildItem -Path "C:\Program Files\OpenSSL\bin" -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libcrypto-1_1-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item (Get-ChildItem -Path "C:\Program Files\OpenSSL\bin" -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | Where-Object {$_.FullName -like '*libssl-1_1-x64*'} | Select-Object FullName).FullName -Destination './app'
          Copy-Item "C:\Windows\System32\msvcp140.dll" -Destination './app'
          Copy-Item "C:\Windows\System32\vcruntime140.dll" -Destination './app'

      - uses: actions/upload-artifact@v4
        with:
          name: bex-win64
          path: ./app/
          compression-level: 9

      - name: Creating a release on Chocolatey
        run: |
          choco pack ./dist/windows/bex.nuspec
          choco apiKey -k ${{ secrets.CHOCO_TOKEN }} -source https://push.chocolatey.org/
          choco push --source https://push.chocolatey.org/
